/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCliente;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hijos
 */
public class FrmCliente extends javax.swing.JFrame {

    ControladorCliente cnt;

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();
        cnt = new ControladorCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnDocumento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtrSocial = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegistra = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        cmbtPersona = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 900, 93));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, -1));

        jLabel2.setText("ID Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel3.setText("Razon Social:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setText("Tipo Persona:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel5.setText("Numero Documento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel7.setText("Teléfono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));
        getContentPane().add(txtnDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 70, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 240, -1));
        getContentPane().add(txtrSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 80, -1));

        btnRegistra.setText("Registrar");
        btnRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistraActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btnModifica.setText("Modificar");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        btnElimina.setText("Eliminar");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        getContentPane().add(btnElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        cmbtPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "J", "N" }));
        getContentPane().add(cmbtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistraActionPerformed
        int id = 0;
        String rSocial = null;
        String tPersona = null;
        String nDocumento = null;
        String Direccion = null;
        String Telefono = null;

        id = Integer.parseInt(txtid.getText());
        rSocial = String.valueOf(txtrSocial.getText());
        tPersona = String.valueOf((String) cmbtPersona.getSelectedItem());
        nDocumento = String.valueOf(txtnDocumento.getText());
        Direccion = String.valueOf(txtDireccion.getText());
        Telefono = String.valueOf(txtTelefono.getText());

        cnt.RegistraCliente(id, rSocial, tPersona, nDocumento, Direccion, Telefono);
        
        limpiar();
    }//GEN-LAST:event_btnRegistraActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        int id;
        String rSocial, tPersona, nDocumento, Direccion, Telefono;
        id = Integer.parseInt(txtid.getText());   
        rSocial = txtrSocial.getText();   
        tPersona = (String) cmbtPersona.getSelectedItem();   
        nDocumento = txtnDocumento.getText();   
        Direccion = txtDireccion.getText();   
        Telefono = txtTelefono.getText();
        
        cnt.ActualizarCliente(id, rSocial, tPersona, nDocumento, Direccion, Telefono);
        
        limpiar();
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
                cnt.MostrarCliente(),
                new String[]{
                    "ID Cliente", "Razon Social","Tipo Persona", "Numero Documento" , "Direccion" , "Telefono"                    
                }
        ));
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        
        int fila = tblCliente.getSelectedRow();
        String idCliente = tblCliente.getValueAt(fila, 0).toString();
        cnt.EliminaCliente(fila, idCliente);
    }//GEN-LAST:event_btnEliminaActionPerformed
    
    public void limpiar(){
        txtid.setText("");
        txtrSocial.setText("");
        txtnDocumento.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistra;
    private javax.swing.JComboBox<String> cmbtPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnDocumento;
    private javax.swing.JTextField txtrSocial;
    // End of variables declaration//GEN-END:variables
}
